name: node_vs_dart_server_comparison
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  http: ^0.13.4
  postgres: ^2.4.3
  json_annotation: ^4.5.0

dev_dependencies:
  lints: ^1.0.1